version: "3"
services:
  follower1:
    build: follower1
    ports:
      - 4000:4000
  follower2:
    build: follower2
    ports:
      - 5000:5000
  leader:
    build: leader
    ports:
      - 3000:3000
